var nameList = [
  "Josie Suarez",
  "Soren Golden",
  "Giuliana Maldonado",
  "Javier Aguirre",
  "Ariah Ortiz",
  "Landon Cabrera",
  "Daleyza Huff",
  "Finnley Fitzpatrick",
  "Annabella Randall",
  "Trenton Barry",
  "Waverly Ahmed",
  "Harry Watkins",
  "Lola Campbell",
  "Christopher Cain",
  "Kendra Jones",
  "William May",
  "Adriana Sanders",
  "Jose Franklin",
  "Angela Villalobos",
  "Reuben Guerra",
  "Edith Nash",
  "Chandler Browning",
  "Princess Sweeney",
  "Nixon Santana",
  "Myra Weeks",
  "Anders Parsons",
  "Maia Robbins",
  "Finnegan Baxter",
  "Lara Truong",
  "Ayan Conner",
  "Alondra Knox",
  "Valentin Cain",
  "Kendra Person",
  "Moses Pineda",
  "Nola Brady",
  "Reed Anthony",
  "Macy Lim",
  "Cal Waller",
  "Whitley Barajas",
  "Brennan Roberts",
  "Paisley Golden",
  "Ryann Valdez",
  "Kyler Morgan",
  "Delilah Kirk",
  "Alessandro Orr",
  "Alaiya Vasquez",
  "Rowan Ramos",
  "Alice Holloway",
  "Sutton Cabrera",
  "Daleyza Kaur",
  "Augustine Parsons",
  "Maia Gregory",
  "Travis Montgomery",
  "Evangeline Warner",
  "Jaxton McGee",
  "Kayleigh Velez",
  "Kareem Silva",
  "Lucia Delarosa",
  "Osiris Hernandez",
  "Camila Lim",
  "Cal Potter",
  "Rory Townsend",
  "Alexis Ortega",
  "Lilah Clay",
  "Yosef Heath",
  "Amani Henderson",
  "Beau Collins",
  "Kinsley Davenport",
  "Dariel Bartlett",
  "Aubrielle Hayden",
  "Leroy Ponce",
  "Aileen Barrera",
  "Makai Grant",
  "Alaina Harrell",
  "Nelson Madden",
  "Violette Winters",
  "Deandre Hess",
  "Kaliyah Gibbs",
  "Deacon Snow",
  "Alexia Garrison",
  "Noe Washington",
  "Valerie McDaniel",
  "Major Weber",
  "Alayah Harris",
  "Samuel McDowell",
  "Rayna Thomas",
  "Logan Sexton",
  "Ellen Conner",
  "Phillip Norman",
  "Malani Harrison",
  "Gavin Grant",
  "Alaina Hess",
  "Lawrence Phan",
  "Elsa Woodward",
  "Jeremias Jennings",
  "Palmer Hoffman",
  "Steven Hodges",
  "Eve Watson",
  "Greyson McDaniel",
  "Dahlia Greer",
  "Koda Nash",
  "Novah Lynch",
  "Zane Rivera",
  "Lillian Hodges",
  "Alonzo Lara",
  "Heidi Taylor",
  "Jackson Knox",
  "Kallie Ruiz",
  "Austin Guerra",
  "Edith McCullough",
  "Briar Gross",
  "Angel Watts",
  "Dakota McClure",
  "Estella Warren",
  "Abel Flores",
  "Emilia Norris",
  "Cairo Poole",
  "Bonnie Medina",
  "George Murphy",
  "Bella Wood",
  "Carson Bradley",
  "Vanessa Richards",
  "Holden Howard",
  "Sophie Ware",
  "Tadeo Wallace",
  "Arianna Palmer",
  "Theo Conner",
  "Alondra Bush",
  "Tyson Clay",
  "Aliana Yang",
  "Malcolm Foley",
  "Zaylee Arias",
  "Alec Herrera",
  "Ximena Best",
  "Harlem Rowe",
  "Matilda Kerr",
  "Louie Jordan",
  "Adalynn Arroyo",
  "Alberto Knox",
  "Kallie Schroeder",
  "Izaiah Olsen",
  "Oaklyn Carson",
  "Ares Burke",
  "Vera Estes",
  "Hakeem Middleton",
  "Madalyn Gillespie",
  "Forest Farrell",
  "Kassidy Solis",
  "Ronin Cortez",
  "Haven Snyder",
  "Thiago Buckley",
];

const comments = [
  "Hey everyone, thanks for joining the chat!",
  "Let me know if you have any questions?",
  "I'm learning so much from this stream.",
  "Thanks for sharing your knowledge!",
  "I'm so glad I found this stream.",
  "Thanks for making this stream so interactive.",
  "I'm so glad I subscribed to your channel.",
  "I always enjoy your streams.",
  "Thanks for the giveaway, I'm so excited to win!",
  "I'm really looking forward to your next stream!",
  "So helpful!",
  "Amazing!",
  "Love it!",
  "Spot on!",
  "Exactly what I needed!",
  "Hey, great stream! I'm really enjoying it.",
  "Thanks for answering my question!",
  "I love your content! Keep up the great work.",
  "This is so interesting! I'm learning a lot.",
  "I'm having a lot of fun! Thanks for streaming.",
  "You're so funny! I'm laughing so hard.",
  "You're so talented! I'm amazed.",
  "I'm so glad I found your channel.",
  "I'm really looking forward to your next stream!",
  "Thanks for the giveaway! I'm so excited to win.",
  "I'm having a great time in the chat!",
  "I'm so glad to be a part of this community.",
  "Thanks for making me feel welcome.",
  "I'm so happy to be here.",
  "I'm having a blast!",
  "This is the best stream ever!",
  "Brilliant!",
  "You nailed it!",
  "Your content always brightens my day!",
  "I'm hooked on your channel. Can't stop watching!",
  "Big fan here! Keep inspiring us.",
  "I've been binge-watching your videos all week!",
  "Your positivity is contagious.",
  "Just joined the stream. What did I miss?",
  "I'm amazed by your creativity.",
  "Your channel is my go-to for inspiration.",
  "Shoutout to the amazing community here!",
  "I've learned so much from your videos. Thank you!",
  "Your energy is infectious. Love tuning in.",
  "Let's keep the chat positive and respectful!",
  "I've shared your channel with all my friends.",
  "You're making a difference with your content.",
  "I appreciate the effort you put into making it.",
  "Can't wait to see what's next on your channel!",
  "Sending virtual hugs to everyone in the chat!",
  "Short and sweet, love it!",
  "This is gold!",
  "Perfect!",
  "Thanks a bunch!",
  "Mind blown!",
  "Great content! Keep it up!",
  "I love this channel!",
  "Awesome stream! I'm enjoying it a lot.",
  "Inspiring content.Keep it coming!",
  "Your videos motivate me daily.",
  "You're a positive force online.",
  "Grateful for your uplifting messages.",
  "Your channel spreads joy effortlessly.",
  "Impressive content. Well done!",
  "You bring smiles to many faces.",
  "Your channel brightens my day.",
  "You're making a difference, truly.",
  "Your authenticity shines through.",
  "Refreshing content. Love it!",
  "You're a ray of sunshine.",
  "Positive vibes all the way!",
  "You're a role model for many.",
  "Thanks for being so genuine.",
  "Love your creative approach.",
  "Your passion is inspiring.",
  "Your positivity is contagious.",
  "You make the internet better.",
  "You're a source of inspiration.",
  "Your videos are impactful.",
  "You make learning enjoyable.",
  "Appreciate your valuable insights.",
  "You're a true content creator.",
  "Your dedication is admirable.",
  "Your channel brings joy to many.",
  "Thanks for sharing your wisdom.",
  "Your energy is infectious!",
  "You create smiles effortlessly.",
  "Your presence is uplifting.",
  "Hi everyone! How's everyone doing today?",
  "This is so interesting! I'm learning a lot.",
  "Shoutout to the amazing moderators!",
  "Can't wait for the next video!",
  "Greetings from [Your Location]!",
  "I just subscribed! Your channel is amazing.",
  "Thanks for the shoutout! You made my day.",
  "Can't get enough!",
  "Incredible!",
  "You rock!",
  "Genius!",
  "Spectacular!",
  "Top-notch!",
  "You make learning enjoyable, thank you for that!",
  "Your information and content is excellent",

]

export const truncateText = (text, maxLength) => {
  if (text.length <= maxLength) {
    return text;
  } else {
    return text.slice(0, maxLength) + "...";
  }
};

export const generateRandomName = () => {
  var finalName = nameList[Math.floor(Math.random() * nameList.length)];
  return finalName
}

export const generateRandomComment = () => {
  const randomComment = comments[Math.floor(Math.random() * comments.length)];
  return randomComment;
}

// Generating Random chat for Live Chat
// export function generateRandomComment(length) {
//   let result = "";
//   const characters =
//     "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
//   const charactersLength = characters.length;
//   let counter = 0;
//   while (counter < length) {
//     result += characters.charAt(Math.floor(Math.random() * charactersLength));
//     counter += 1;
//   }
//   return result;
// }