var nameList = [
  "Josie Suarez",
  "Soren Golden",
  "Giuliana Maldonado",
  "Javier Aguirre",
  "Ariah Ortiz",
  "Landon Cabrera",
  "Daleyza Huff",
  "Finnley Fitzpatrick",
  "Annabella Randall",
  "Trenton Barry",
  "Waverly Ahmed",
  "Harry Watkins",
  "Lola Campbell",
  "Christopher Cain",
  "Kendra Jones",
  "William May",
  "Adriana Sanders",
  "Jose Franklin",
  "Angela Villalobos",
  "Reuben Guerra",
  "Edith Nash",
  "Chandler Browning",
  "Princess Sweeney",
  "Nixon Santana",
  "Myra Weeks",
  "Anders Parsons",
  "Maia Robbins",
  "Finnegan Baxter",
  "Lara Truong",
  "Ayan Conner",
  "Alondra Knox",
  "Valentin Cain",
  "Kendra Person",
  "Moses Pineda",
  "Nola Brady",
  "Reed Anthony",
  "Macy Lim",
  "Cal Waller",
  "Whitley Barajas",
  "Brennan Roberts",
  "Paisley Golden",
  "Ryann Valdez",
  "Kyler Morgan",
  "Delilah Kirk",
  "Alessandro Orr",
  "Alaiya Vasquez",
  "Rowan Ramos",
  "Alice Holloway",
  "Sutton Cabrera",
  "Daleyza Kaur",
  "Augustine Parsons",
  "Maia Gregory",
  "Travis Montgomery",
  "Evangeline Warner",
  "Jaxton McGee",
  "Kayleigh Velez",
  "Kareem Silva",
  "Lucia Delarosa",
  "Osiris Hernandez",
  "Camila Lim",
  "Cal Potter",
  "Rory Townsend",
  "Alexis Ortega",
  "Lilah Clay",
  "Yosef Heath",
  "Amani Henderson",
  "Beau Collins",
  "Kinsley Davenport",
  "Dariel Bartlett",
  "Aubrielle Hayden",
  "Leroy Ponce",
  "Aileen Barrera",
  "Makai Grant",
  "Alaina Harrell",
  "Nelson Madden",
  "Violette Winters",
  "Deandre Hess",
  "Kaliyah Gibbs",
  "Deacon Snow",
  "Alexia Garrison",
  "Noe Washington",
  "Valerie McDaniel",
  "Major Weber",
  "Alayah Harris",
  "Samuel McDowell",
  "Rayna Thomas",
  "Logan Sexton",
  "Ellen Conner",
  "Phillip Norman",
  "Malani Harrison",
  "Gavin Grant",
  "Alaina Hess",
  "Lawrence Phan",
  "Elsa Woodward",
  "Jeremias Jennings",
  "Palmer Hoffman",
  "Steven Hodges",
  "Eve Watson",
  "Greyson McDaniel",
  "Dahlia Greer",
  "Koda Nash",
  "Novah Lynch",
  "Zane Rivera",
  "Lillian Hodges",
  "Alonzo Lara",
  "Heidi Taylor",
  "Jackson Knox",
  "Kallie Ruiz",
  "Austin Guerra",
  "Edith McCullough",
  "Briar Gross",
  "Angel Watts",
  "Dakota McClure",
  "Estella Warren",
  "Abel Flores",
  "Emilia Norris",
  "Cairo Poole",
  "Bonnie Medina",
  "George Murphy",
  "Bella Wood",
  "Carson Bradley",
  "Vanessa Richards",
  "Holden Howard",
  "Sophie Ware",
  "Tadeo Wallace",
  "Arianna Palmer",
  "Theo Conner",
  "Alondra Bush",
  "Tyson Clay",
  "Aliana Yang",
  "Malcolm Foley",
  "Zaylee Arias",
  "Alec Herrera",
  "Ximena Best",
  "Harlem Rowe",
  "Matilda Kerr",
  "Louie Jordan",
  "Adalynn Arroyo",
  "Alberto Knox",
  "Kallie Schroeder",
  "Izaiah Olsen",
  "Oaklyn Carson",
  "Ares Burke",
  "Vera Estes",
  "Hakeem Middleton",
  "Madalyn Gillespie",
  "Forest Farrell",
  "Kassidy Solis",
  "Ronin Cortez",
  "Haven Snyder",
  "Thiago Buckley",
];

const comments = [
  "Hey everyone, thanks for joining the chat!",
  "What are you most excited about for the stream today?",
  "Let me know if you have any questions, and I'll do my best to answer them.",
  "I'm really enjoying this stream, so thanks for hosting!",
  "I'm learning so much from this stream, thanks for sharing your knowledge!",
  "This stream is so entertaining, I can't stop watching!",
  "I'm so glad I found this stream, it's been a great way to spend my day.",
  "Thanks for making this stream so interactive, it's really fun to be a part of.",
  "I'm really impressed with your skills, you're a great streamer!",
  "I'm so glad I subscribed to your channel, I always enjoy your streams.",
  "Thanks for the giveaway, I'm so excited to win!",
  "I'm really looking forward to your next stream!",
  "So helpful!",
  "Amazing!",
  "Love it!",
  "Spot on!",
  "Exactly what I needed!",
  "Brilliant!",
  "You nailed it!",
  "Short and sweet, love it!",
  "This is gold!",
  "Perfect!",
  "Thanks a bunch!",
  "Mind blown!",
  "Can't get enough!",
  "Incredible!",
  "You rock!",
  "Genius!",
  "Spectacular!",
  "Top-notch!",
  "Your channel deserves way more subscribers, amazing content!",
  "I've been binge-watching your videos, can't get enough!",
  "You make learning enjoyable, thank you for that!",
  "I wish more creators were as informative as you are.",
  "The way you break down concepts is so clear and concise!",
  "Your video quality is excellent, and the information is even better!",
  "I've recommended your channel to all my friends – it's that good!",
]

export const generateRandomName = () => {
  var finalName = nameList[Math.floor(Math.random() * nameList.length)];
  return finalName
}

export const generateRandomComment = () => {
  const randomComment = comments[Math.floor(Math.random() * comments.length)];
  return randomComment;
}
